### ISSUE TITLE
ImportError for module routes when launching

### ISSUE THREAD

**Issue by neggert** [dmwm/cmssh#1]
When I start cmssh, I get the following output:

ImportError                               Traceback (most recent call last)
/Library/Frameworks/EPD64.framework/Versions/7.1/lib/python2.7/site-packages/IPython/core/extensions.py in load_extension(self, module_str)
     85         if module_str not in sys.modules:
     86             with prepended_to_syspath(self.ipython_extension_dir):
---> 87                 **import**(module_str)
     88         mod = sys.modules[module_str]
     89         return self._call_load_ipython_extension(mod)

/Users/nic/cms/soft/.ipython/extensions/cmssh_extension.py in <module>()
     19 from   cmssh.iprint import PrintManager
     20 from   cmssh.debug import DebugManager
---> 21 from   cmssh.cms_cmds import dbs_instance, Magic
     22 from   cmssh.cms_cmds import lookup, cms_ls, cms_cp, verbose
     23 from   cmssh.cms_cmds import cms_rm, cms_rmdir, cms_mkdir, cms_root, cms_xrdcp

/Users/nic/cms/soft/cmssh/src/cmssh/cms_cmds.py in <module>()
     15 from cmssh.filemover import copy_lfn, rm_lfn, mkdir, rmdir, list_se
     16 from cmssh.utils import list_results
---> 17 from cmssh.cmsfs import dataset_info, block_info, file_info, site_info
     18 from cmssh.cmsfs import CMSFS, apply_filter, validate_dbs_instance
     19 from cmssh.cms_urls import dbs_url

/Users/nic/cms/soft/cmssh/src/cmssh/cmsfs.py in <module>()
     10 import re
     11 import json
---> 12 import routes
     13 import urllib
     14 import urllib2

ImportError: No module named routes

**Comment by vkuznet** [comment]
The Routes packages should be installed via cmssh_install.py script. You can also get them from http://pypi.python.org/packages/source/R/Routes/

**Comment by neggert** [comment]
I installed routes using easy_install and now I'm getting another error:

## [TerminalIPythonApp] Error in loading extension: cmssh_extension

AttributeError                            Traceback (most recent call last)
/Library/Frameworks/EPD64.framework/Versions/7.1/lib/python2.7/site-packages/IPython/core/extensions.py
in load_extension(self, module_str)
     87                 **import**(module_str)
     88         mod = sys.modules[module_str]
---> 89         return self._call_load_ipython_extension(mod)
     90
     91     def unload_extension(self, module_str):

/Library/Frameworks/EPD64.framework/Versions/7.1/lib/python2.7/site-packages/IPython/core/extensions.py
in _call_load_ipython_extension(self, mod)
    119     def _call_load_ipython_extension(self, mod):
    120         if hasattr(mod, 'load_ipython_extension'):
--> 121             return mod.load_ipython_extension(self.shell)
    122
    123     def _call_unload_ipython_extension(self, mod):

/Users/nic/cms/soft/.ipython/extensions/cmssh_extension.py in
load_ipython_extension(ipython)
    186     # This allows you do to things like register new magics, plugins or

```
187     # aliases.
```

--> 188     main(ipython)

/Users/nic/cms/soft/.ipython/extensions/cmssh_extension.py in main(ipython)
    166 #    ip.displayhook.prompt1.p_template = \

```
167 #        '\C_LightBlue[\C_LightCyan%s\C_LightBlue]|\#> ' % prompt
```

--> 168     ip.prompt_manager.in_template = '%s|#> ' % prompt
    169
    170     # define dbsh banner

AttributeError: 'TerminalInteractiveShell' object has no attribute
'prompt_manager'

Something must be going wrong with the installation. Is there an
installation log somewhere that I can send you?

Thanks,
Nic

On Mon, Jan 23, 2012 at 11:33 AM, Valentin Kuznetsov
reply@reply.github.com
wrote:

**Comment by vkuznet** [comment]
yep, looks like you have installation issue. In this case the error seems improper ipython install.

Could you please wipe out soft area and try again. I actually quit often commit recently and it may be that you got some untested installer version.

BTW, all logs are available, you can search for them as simple as
find soft/ -name "*.log"
You'll get lis of logs per each package cmssh_install.py installs.

**Comment by vkuznet** [comment]
But it may be python2.7 issue, since I see from your log that you're using it. So far I test my installation using python 2.6. I tried to avoid system installed packages, so everything should be self consistent, therefore Routes should be installed inside soft area. Let's see what you get after clean install.

**Comment by neggert** [comment]
I tried a re-install and I still get the same problem. Should I try
setting up a python 2.6 install using virtualenv?

On Mon, Jan 23, 2012 at 12:48 PM, Valentin Kuznetsov
reply@reply.github.com
wrote:

**Comment by neggert** [comment]
I think this is resolved now
