### ISSUE TITLE
Enter PEM pass phrase:

### ISSUE THREAD

**Issue by neggert** [dmwm/cmssh#10]
I'm often prompted to enter a PEM pass phrase when trying to copy a file from a storage element. Sometimes I'm asked for every file. This is quite annoying when I'm trying to copy every file in a dataset using a for loop.

**Comment by vkuznet** [comment]
How you'd like to handle it? Should I introduce a new passphrase command which will store it? Since the passphrase is asked by GRID middleware tools, I can wrap the call with echo, e.g.
echo <passphrase> | srm-cp
I think it will work.

**Comment by neggert** [comment]
I guess my question is, why does it only happen sometimes? I just quit
cmssh, restarted it, and tried to copy all the files from the same
dataset using the same commands, and it never prompted me for a
password. To me that indicates that it's possible to do this without
the raising the prompt every time, it's just a matter of figuring out
under what circumstances the prompt appears.

On Tue, Apr 10, 2012 at 1:17 PM, Valentin Kuznetsov
reply@reply.github.com
wrote:

**Comment by vkuznet** [comment]
Ahh, well, that because at startup of cmssh I invoke voms-proxy-init command which setup a proxy from your certificate. This proxy has limited lifetime and needs to be renewed. Therefore you have additional commands vomsinit, vomsinfo, etc. You can use them to renew your proxy. But I think I can run additional thread to do that for lazy users :)

**Comment by neggert** [comment]
Ah, no problem. I can run them manually. I just wasn't sure how to do
it manually.

On Tue, Apr 10, 2012 at 1:41 PM, Valentin Kuznetsov
reply@reply.github.com
wrote:

**Comment by vkuznet** [comment]
I've added voms_monitor which will renew user proxy. Closing the ticket.
