### ISSUE TITLE
dqueue-summary

### ISSUE THREAD

**Issue by neggert** [dmwm/cmssh#14]
The output of `dqueue` when lots of jobs are in the queue is somewhat long and messy. Perhaps add a way to get just a summary of the number of jobs running, waiting, and finished.

I can think of two approaches for this.

1) Change the current `dqueue` command to print something like:

```
Waiting:
job1
job2
job3
job4
job5
...
+ 73 other jobs (use dqueue --full to see all jobs)
```

2) Leave `dqueue` as it is. Add a new command `dqueue-summary` or `dqueue --summary` which just prints the number of jobs in the in progress, waiting, and finshed states.

**Comment by vkuznet** [comment]
By default dqueue will print summary, to get full listing you'll need to provide 'list' argument.
