### ISSUE TITLE
How to change dbs_instance

### ISSUE THREAD

**Issue by neggert** [dmwm/cmssh#2]
I'm not sure if this is a bug or if I just don't know what I'm doing. I'm trying to change the dbs instance. I assume that I should be able to do :

dbs_instance cms_dbs_ph_analysis_01

but that gives me an invalid DBS instance message. Is this not working properly or am I doing something wrong. Implementing dbs_instance --help might be useful in the future.

**Comment by vkuznet** [comment]
Ok, it's a bug. I'll fix it in next release. And yes, the option may be handful. I'll have a look.

**Comment by vkuznet** [comment]
Should be resolved in v0.10.
