### ISSUE TITLE
Check code to look-up libreadline5

### ISSUE THREAD

**Issue by vkuznet** [dmwm/cmssh#47]
One user suggested that cmsh_install.py may incorrectly check presence of libreadline5 on a system. The /sbin/ldconfig -p may return a list where the first match may not be proper readline

**Comment by heinzK1X** [comment]
Hello!
Indeed, that has been fixed earlier. The installation went fine, with the current version of cmssh_install.py directly from github.
There are wrong links, from where I downloaded old versions of the installer previously:
http://vkuznet.github.com/cmssh/
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookCmsshTutorial
It would be nice to have the file somewhere downloadable. From github I had to paste and copy..

cheers,
Heiner

**Comment by vkuznet** [comment]
Hi Heiner, I'm glad that installation works for you. Regarding the links, I've fixed them all on a Twiki page (sorry the cmssh has migrated from my personal repository to official CMS DMWM one). Regarding paste-copy, I'm not sure I understand since the github page which provide installer is a normal html page which you can just save (using your browser shortkey or File/Save menu).

My understanding that readline5 issue did not bother you during installation anymore (with new installer), right? Anyhow I'll check the code later (so I'll keep this ticket open).

**Comment by heinzK1X** [comment]
Yes, right. The readline problem was solved with the new install script.

When I'm on this page, I don't find a download link for the actual file:
https://github.com/dmwm/cmssh/blob/master/cmssh_install.py
So I just copied from the webpage window =)

Best, Heiner

Am 19.02.2013 um 15:37 schrieb Valentin Kuznetsov:

**Comment by vkuznet** [comment]
> Yes, right. The readline problem was solved with the new install script. 

ok

> When I'm on this page, I don't find a download link for the actual file: 
> https://github.com/dmwm/cmssh/blob/master/cmssh_install.py 
> So I just copied from the webpage window =) 

when you're on this page it is raw file and the browser allow you to save it, just open in your browser File/Save as, no need to paste/cut.

**Comment by heinzK1X** [comment]
Ok, now I see it: I was not on the raw but the regular page:
https://github.com/dmwm/cmssh/blob/master/cmssh_install.py
and this is raw:
https://raw.github.com/dmwm/cmssh/master/cmssh_install.py
And I had to remove "/blob" from the url to make it work. But anyways, with new download links on the other pages, this will work. To avoid confusion, it maybe good to remove cmssh from your private account? I just googled and landed on your private one first.. Thanks a lot!

**Comment by vkuznet** [comment]
> Ok, now I see it: I was not on the raw but the regular page: 
> https://github.com/dmwm/cmssh/blob/master/cmssh_install.py 
> and this is raw: 
> https://raw.github.com/dmwm/cmssh/master/cmssh_install.py 
> And I had to remove "/blob" from the url to make it work.

the github.com page has a "Edit Raw Blame History" links, so you can make your choice, no need to tweak the URL itself.

> But anyways, with new download links on the other pages, this will work. To avoid confusion, it maybe good to remove cmssh from your private account? I just googled and landed on your private one first..

My private cmssh page is a "fork" of official repository and I need to use it for branches/merging/etc. Since I made it first, google is smart enough to show it first, but eventually, it will be reverted once more people will access the later one.

**Comment by heinzK1X** [comment]
Ok, Sorry for that and showing me around github =/

**Comment by vkuznet** [comment]
I checked the code and it does proper things, closing the ticket.
