### ISSUE TITLE
linux installation lacks two packages

### ISSUE THREAD

**Issue by heinzK1X** [dmwm/cmssh#48]
Hello,

I just installed on lxplus. Two pip packages were missing to make it work:
pytz
pycrypto

I just added then in line 825 of cmssh_install.py to the std_pkgs list.

cheers, Heiner

**Comment by vkuznet** [comment]
could you please be more explicit, which part didn't work? I'm pretty sure I install cmssh on lxplus several times and did not required neither pytz or pycrypto. I'm not against adding them into std_pkgs, but rather would like to understand the reason why they are needed and what did not work for you.

**Comment by heinzK1X** [comment]
Hello,

sorry, you're right, I should have asked that myself. 
The machine itself is not part of lxplus, but based at cern and running a fresh SLC5.9 installation.

Ze problem: Installation went fine, but upon starting an exception was thrown: 
(1) no module named pytz, after adding to script and installing again, 
(2) no module named Crypto, for which I added pycrypto. 

After this, cmssh started properly. After entering passphrase for my user key.kem I get 
"ERROR: writing RSA key"
but some grid tools do work properly, e.g. ls T2_DE_RWTH:/user/... 
But this is probably another issue..

Best,
    Heiner

Am 19.02.2013 um 15:40 schrieb Valentin Kuznetsov:

**Comment by vkuznet** [comment]
what is the name of machine? Is it accessible for anyone with lxplus account?

**Comment by heinzK1X** [comment]
you can try from lxplus:
pcac3b04.cern.ch 
but I had to manually my own account. Please try!

Am 19.02.2013 um 17:30 schrieb Valentin Kuznetsov:

**Comment by vkuznet** [comment]
nope, it does not let me in, so it does not use standard lxplus authentication.

Anyway, I need to check if addition of pytz/pycrypto will not break other platforms (SLC5 and OSX). Since cmssh is installed with pip, you can add any package including these two once cmssh is installed, e.g.

cmssh> pip install pycrypto

**Comment by heinzK1X** [comment]
I tried that in the first place, but after the "no module named ..." exception, the environment wasn't loaded completely. I was left with a bare ipython, I guess, where pip wasn't yet loaded. Or at least the pip command didn't work.

**Comment by vkuznet** [comment]
Fixed: 042622dc9b309ec5114854ef597cc8b46840cd30
