### ISSUE TITLE
cp by lfn doesn't work

### ISSUE THREAD

**Issue by neggert** [dmwm/cmssh#6]
I'm having a problem copying by lfn. See the error message below. This file is in cms_dbs_ph_analysis_01, so maybe that has something to do with the problem. It looks fine if I prepend the site name to the lfn, i.e. T1_US_FNAL_Buffer:/store/user/...

cp /store/user/neggert/TT_TuneZ2_7TeV-mcatnlo/MCTSusy_Skim_Mar2012//7b5af1bfe3424f60f0db5b5f14cf327a/MCTSusySkimMar2012_100_1_kYt.root .
Traceback (most recent call last):
  File "/Users/nic/cms/soft/cmssh/src/cmssh/cms_cmds.py", line 487, in cms_cp
    status = copy_lfn(src, dst, verbose, background)
  File "/Users/nic/cms/soft/cmssh/src/cmssh/filemover.py", line 610, in copy_lfn
    status = FM_SINGLETON.copy(lfn, dst, verbose, background)
  File "/Users/nic/cms/soft/cmssh/src/cmssh/filemover.py", line 456, in copy
    for cmd in srmcp("srm-copy", lfn, dst, verbose):
  File "/Users/nic/cms/soft/cmssh/src/cmssh/filemover.py", line 307, in srmcp
    raise Exception(msg)
Exception: LFN: /store/user/neggert/TT_TuneZ2_7TeV-mcatnlo/MCTSusy_Skim_Mar2012//7b5af1bfe3424f60f0db5b5f14cf327a/MCTSusySkimMar2012_100_1_kYt.root
No replicas found
{u'phedex': {u'request_date': u'2012-04-06 18:09:06 UTC', u'request_timestamp': 1333735746.04251, u'call_time': u'0.01102', u'instance': u'prod', u'request_call': u'fileReplicas', u'request_url': u'http://cmsweb.cern.ch:7001/phedex/datasvc/json/prod/fileReplicas', u'request_version': u'2.3.8', u'block': []}}
Wrong argument '/store/user/neggert/TT_TuneZ2_7TeV-mcatnlo/MCTSusy_Skim_Mar2012//7b5af1bfe3424f60f0db5b5f14cf327a/MCTSusySkimMar2012_100_1_kYt.root .'

**Comment by vkuznet** [comment]
This is done.
